global:
  name: OpenJS Foundation Interactive Landscape
  short_name: OpenJSF
  repo: dankohn/openjsf-landscape
  website: 'https://openjsf-landscape.netlify.com'
  short_domain: openjsf-landscape.netlify.com
  company_url: 'https://openjsf.org'
  membership: OpenJS Foundation Member Company
  email: info@openjsf.org
  self: 'https://www.crunchbase.com/organization/open-js-foundation'
  slack_channel: T08PSQ7BQ/BQKAV2KDG/ixNxV2AI4q4mG7aYKgwD53C8
  meta:
    title: OpenJS Foundation Landscape
    fb_admin: alex.contini.94
    description: 'Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets'
    twitter: openjsf
    google_site_verification: M_GmEYdzsEnvJiIcvfj7gmczKsme1N5rd9RwRD35Y98
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  flags:
    companies: OpenJS Foundation Member Company
twitter:
  search: openjsf-landscape.netlify.com'
  url: 'https://openjsf-landscape.netlify.com'
  text: OpenJS Foundation Landscape from @openjsf
relation:
  label: OpenJS Foundation Relation
  url: openjsf
  values:
    - id: hosted
      label: OpenJS Foundation Projects
      children:
        - id: at_large
          label: At Large
          prefix: OpenJS Foundation
          tag: At Large
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: OpenJS Foundation At Large
          big_picture_color: 'rgb(24,54,114)'
        - id: growth
          label: Growth
          prefix: OpenJS Foundation
          tag: Growth
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: OpenJS Foundation Growth
          big_picture_color: 'rgb(24,54,114)'
        - id: sandbox
          label: Sandbox
          prefix: OpenJS Foundation
          tag: Sandbox
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: OpenJS Foundation Sandbox
          big_picture_color: 'rgb(24,54,114)'
          additional_relation: member
    - id: company
      label: OpenJS Foundation Members
      tag: Company
      big_picture_order: 3
    - id: member
      label: OpenJS Foundation Member Products/Projects
      tag: OpenJS Foundation Member
    - id: false
      label: Non-OpenJS Foundation Member Products/Projects
      url: 'no'
membership:
  Platinum:
    name: OpenJS Foundation
    label: Premier Member
    funding: Premier
    is_large: true
  General:
    name: OpenJS Foundation
    label: Member
    funding: General
  Associate:
    name: OpenJS Foundation
    label: Associate
    funding: Associate
  'false':
    funding: 'No'
home:
  header: >
    <h1>OpenJS Foundation Interactive Landscape</h1> The OpenJS Foundation landscape (<a target="_blank" href="images/landscape.png">png</a>,  <a target="_blank"
    href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the  <a href="http://landscape.cncf.io">CNCF Landscape</a> and
    based on the same open source code.
  footer: null
ads:
  - url: 'https://events19.linuxfoundation.org/events/kubecon-cloudnativecon-europe-2020/?utm_source=openjsf_landscape&utm_medium=web&utm_campaign=kccnceu20'
    image: /images/info1.jpg
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /category=openjs-foundation-member-company&format=card-mode&grouping=category
    label: Member cards
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: OpenJS Foundation Landscape
    fullscreen_header: See the interactive landscape at openjsf-landscape.netlify.com
    size:
      width: 950
      height: 470
    fullscreen_size:
      width: 950
      height: 470
    elements:
      - type: HorizontalCategory
        category: Projects
        rows: 2
        width: 585
        height: 200
        top: 10
        left: 0
        color: 'rgb(104, 145, 145)'
        fit_width: true
      - type: HorizontalCategory
        category: OpenJS Foundation Member Company
        rows: 3
        width: 900
        height: 170
        top: 230
        left: 0
        color: 'rgb(124, 200, 182)'
        fit_width: true
      - type: LandscapeInfo
        width: 280
        height: 200
        top: 10
        left: 620
        children:
          - type: text
            text: >-
              This OpenJS Foundation Landscape is a living document that developers, investors, vendors, researchers and others can use as a resource to better
              understand the OpenJSF ecosystem.
            top: 55
            left: 120
            right: 20
            font_size: 10
          - type: image
            image: qr.svg
            top: 55
            left: 10
            width: 90
            height: 90
          - type: title
            title: openjsf-landscape.netlify.com
            top: 150
            left: 19
            font_size: 12
          - type: image
            image: left-logo.svg
            width: 110
            right: 160
            top: 10
          - type: image
            image: right-logo.svg
            width: 109
            right: 25
            top: 15
test:
  header: OpenJS Foundation Interactive Landscape
  section: Growth
  logo: operator-fabric.svg
